syntax = "proto3";

package genplan;

service GenPlanService {
  rpc GeneratePlan (GeneratePlanRequest) returns (GeneratePlanResponse);
}

message GeneratePlanRequest {
  string music_name = 1;
  string music_url = 2;
  double duration = 3;
}

message GeneratePlanResponse {
  repeated PlannedSegment segments = 1;
}

message PlannedSegment {
  string action_id = 1;
  double start_time = 2;
  double duration = 3;
  string action_type = 4;
  Color color = 5;
}

message Color {
  int32 r = 1;
  int32 g = 2;
  int32 b = 3;
  int32 a = 4;
}
