open:
  api:
    title: Alpha Mini API
    version: 1.0.0
    description: SEP project with AlphaMini API
    serverUrl: ${OPEN_API_SERVERURL:http://localhost:8081}

springdoc:
  api-docs:
    server:
      url: ${OPEN_API_SERVERURL:http://localhost:8081}
  swagger-ui:
    path: /swagger

logging:
  level:
    org:
      springdoc: INFO
      springframework: INFO
      io: INFO
