open:
  api:
    title: Alpha Mini API
    version: 1.0.0
    description: SEP project with AlphaMini API
    serverUrl: ${OPEN_API_SERVERURL:http://localhost:8081}

springdoc:
  api-docs:
    server:
      url: ${OPEN_API_SERVERURL:http://localhost:8081}
  swagger-ui:
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true

logging:
  level:
    org:
      springdoc: INFO
      springframework: INFO
      io: INFO

spring:
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}

