name: Build and Deploy to Ubuntu

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set execute permission for mvnw
        run: chmod +x ./mvnw

      # Bước 2: Set up JDK 24
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      # Bước 3: Build ứng dụng bằng Maven
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      # Bước 4: Copy file JAR qua server Ubuntu qua SSH
      - name: Copy JAR to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ./target/*.jar
          target: ~/alpha-code-api/

      # Bước 5: SSH remote để khởi động ứng dụng trên server
      - name: Run Spring Boot app on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            pkill -f 'java -jar' || true
            # Change directory to where the JAR was actually copied by scp-action
            cd ~/alpha-code-api/
            nohup java -jar *.jar > app.log 2>&1 &
            sleep 5 # Give the Java process a moment to detach
            exit 0