name: Build and Deploy to Ubuntu

on:
  push:
    branches:
      - deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Cho phép chạy ./mvnw
      - name: Set execute permission for mvnw
        run: chmod +x ./mvnw

      # 3. Setup JDK 24
      - name: Setup JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      # 4. Build bằng Maven, skip test
      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      # 5. Copy file JAR sang server đúng thư mục target
      - name: Copy JAR to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ./target/*.jar
          target: ~/alpha-code-api/target/

      # 6. SSH remote chạy app trong tmux để app không bị kill khi SSH đóng
      - name: Run Spring Boot app on server (tmux)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Kill app đang chạy (nếu có)
            pkill -f 'java -jar' || true

            cd ~/alpha-code-api/target

            # Kiểm tra tmux đã có chưa, nếu chưa cài, bạn cần cài tmux trên server 1 lần
            command -v tmux || (echo "tmux not found" && exit 1)

            # Chạy app trong session tmux tên 'springboot'
            tmux kill-session -t springboot || true
            tmux new-session -d -s springboot "java -jar alpha-code-api-0.0.1-SNAPSHOT.jar > app.log 2>&1"
